.PHONY: clean

grad2: lab2.h grad2.c
	clang -o grad2 -Wall grad2.c -lm

grad3: lab2.h grad3.c
	clang -o grad3 -Wall grad3.c -lm

circ:  lab2.h circ.c
	clang -o circ -Wall circ.c -lm

clean:
	rm -f grad2 grad3 circ *.ppm